name: 'movie-list'

services:
  postgres:
    image: postgres:latest
    environment:
      - "TZ=Europe/Budapest"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=12345678"
    ports:
      - "5432:5432"
